version: '3.7'

services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "5432:5432"
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgres-db:/var/lib/mysql

# # Names our volume
volumes:
  postgres-db: